### ISSUE TITLE
Would like to have a feature to scan on a specific repository branch

### ISSUE THREAD

**Issue by prosenjit87** [SAP/credential-digger#104]
Hello,

It would be great to have a feature to scan on a specific branch of a repository; which will also reduce scan time on a certain circumstances. Kindly consider.

**Comment by marcorosa** [comment]
Thank you @prosenjit87 for your suggestion. We will take care of it.

---

Note to ourselves.

Implement a new function:
- Scan the repository (its snapshot) at a given "moment in time" (i.e., the last commit of a specific branch or a specific commit in history)
- The workflow is similar to 
  - clone the repo
  - checkout the commit
  - scan folder (i.e., don't unroll history, and don't consider diffs)
- Integrate this new feature into the UI

**Comment by marcorosa** [comment]
WIP in branch `feat/scan-snapshot`

Workload tracker:
- [ ] develop in python library
- [ ] integrate in cli
- [ ] integrate in UI 
- [ ] documentation
- [ ] MacOS integration and documentation
- [ ] release

**Comment by marcorosa** [comment]
This feature is out with v3.3.0 (#121 and #129 )

Still TODO: I have to write the documentation. Then I will close this issue (I leave it open until it's really solved, i.e., with the all the needed documentation available)

**Comment by marcorosa** [comment]
The feature is fully integrated and documented now.
