### ISSUE TITLE
Access to model definitions and training/validation data?

### ISSUE THREAD

**Issue by nlykkei** [SAP/credential-digger#108]
Would it be possible to get access to model definitions and training/validation data for the models used in SAP/credential-digger?

I'm interested to see how these models were trained, and to possible contribute to their future development.

Currently it seems that only trained models are available for download.

**Comment by SlimTrabelsi** [comment]
Hi Nicolas,

Thank you for the interest to the project. 
I'll start first with a clarification with regards to the training/validation data. Currently we trained two types of Models, one based on real data that we keep internal (for privacy reasons), and a second one that is open source, that is trained using synthetic generated data. If you are interested we can give you more details on how this data is generated or how to train your own data (already some details are avaialble in our publication [here](https://www.researchgate.net/publication/349402349_Optimizing_Leak_Detection_in_Open-source_Platforms_with_Machine_Learning_Techniques) ). 
If you are interested in contributing to the project or if you want to deploy it in your professional environment , let's then have a call together with the team and discuss this in details. You can join me directly on my e-mail that you will find in the publication ;) .
Best regards
Slim
