### ISSUE TITLE
Docker Image on Windows 10 Error / Fix

### ISSUE THREAD

**Issue by joechav101212** [SAP/credential-digger#185]
The docker image will not start up on Windows 10 using Docker Desktop - it will give you an error "no such file or directory"

It should use a Unix-style line endings instead of Windows.
The following command needs to be ran before cloning the repository: git config --global core.autocrlf false
Then clone the repository and proceed.

So it would be like this:
PS C:\Docker> git config --global core.autocrlf false
PS C:\Docker> git clone https://github.com/SAP/credential-digger.git

After this the docker image runs fine

**Comment by marcorosa** [comment]
Thank you for raising this issue (with fix included). We will test it as soon as possible to reproduce the error and update the Dockerfile accordingly.

**Comment by marcorosa** [comment]
Fixed in [this commit](https://github.com/SAP/credential-digger/commit/e6021f3d9ef4f0f56d55fb23ea6222ed685ffcc3).
Will be merged into `main` branch and released in a few days
