### ISSUE TITLE
Tensorflow error

### ISSUE THREAD

**Issue by sarthakg1234** [SAP/credential-digger#188]
Hello team,
I was running the tool on ubuntu and was running cred-digger via automation in my jenkins using:
while(i< size){
                        sleep(10)
                    sh 'python3 -m credentialdigger scan '+list1[i]+' --similarity --git_token '+server.token+' --sqlite data.db --models PathModel SnippetModel'
                     sleep(10)

04:15:53  2021-08-20 08:15:53.338501: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
04:15:53  2021-08-20 08:15:53.338543: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
04:15:53  2021-08-20 08:15:53.338564: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (sarthakcred-digger): /proc/driver/nvidia/version does not exist
04:15:53  2021-08-20 08:15:53.338813: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
04:15:53  To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
04:15:55  2021-08-20 08:15:54.995171: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
04:15:55  2021-08-20 08:15:54

**Comment by marcorosa** [comment]
Hi @sarthakg1234 thank you for raising this issue.

@melisande1  have you already experienced this error in your ubuntu installation? Are we missing some dependencies that are needed for TensorFlow in Ubuntu, in our README?

**Comment by sarthakg1234** [comment]
Thank you @marcorosa , 
I am running cred-digger on a CPU environment , how do we suppress the above error when no GPU is being used?
thanks

**Comment by sarthakg1234** [comment]
Hi @marcorosa ,
https://github.com/SAP/credential-digger/pull/189
This worked on my machine , cred-digger runs but still warnings come up , need to suppress them..

**Comment by melisande1** [comment]
Hi @sarthakg1234 , @marcorosa, 
These warnings are normal, they just signal no Nvidia GPU is found / Cuda is not installed, they should not prevent the tool from running.
Setting the logging level higher may suppress them, I will look into this matter

**Comment by marcorosa** [comment]
Fixed in #194
