### ISSUE TITLE
variable refactor

### ISSUE THREAD

**Issue by Soontao** [SAP/credential-digger#203]
Hi maintainers, 

For this line: 

https://github.com/SAP/credential-digger/blob/365eedca3eaec201503441046ba0c37937db69e1/ui/server.py#L31

maybe we can set the `DEBUG` variable from environment variable ?

Regards,
Theo

**Comment by marcorosa** [comment]
Hi @Soontao,
thank you for your interest in this project.

Indeed, your suggestion is good. I think I will implement it in the next release (it's just a matter of a few lines of code)

**Comment by marcorosa** [comment]
Fixed in #208
