### ISSUE TITLE
Pull request scan trigger hook

### ISSUE THREAD

**Issue by SlimTrabelsi** [SAP/credential-digger#245]
Add a hook that will trigger a project scan for every pull request sent by the developer

**Comment by pcorni** [comment]
@SlimTrabelsi Is there any update to the current state or when it is planned on your roadmap / backlog.

**Comment by SlimTrabelsi** [comment]
> @SlimTrabelsi Is there any update to the current state or when it is planned on your roadmap / backlog.

We did a feasibility search to have a first idea on how it can be done .. but we lack time and resources to start the implementation for now :(

**Comment by marcorosa** [comment]
Feature released in #250

Future work for this feature is integration with [project piper](https://github.com/SAP/jenkins-library)
