### ISSUE TITLE
Error, blank web page 

### ISSUE THREAD

**Issue by tobbyjayi04** [SAP/credential-digger#259]
MacBook-Pro-2:credential-digger John$ sudo docker-compose up --build
Password:
WARN[0000] The "SSL_certificate" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_private_key" variable is not set. Defaulting to a blank string. 
[+] Building 0.7s (17/17) FINISHED                                              
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 32B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/python:3.9-bullseye     0.6s
 => [ 1/12] FROM docker.io/library/python:3.9-bullseye@sha256:7af616b9341  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 3.09kB                                        0.0s
 => CACHED [ 2/12] RUN pip install flask_jwt_extended Flask python-dotenv  0.0s
 => CACHED [ 3/12] RUN apt-get update && apt-get install -y libhyperscan5  0.0s
 => CACHED [ 4/12] RUN apt-get install -y dos2unix                         0.0s
 => CACHED [ 5/12] RUN git config --global http.sslverify false            0.0s
 => CACHED [ 6/12] RUN git config --global core.autocrlf false             0.0s
 => CACHED [ 7/12] RUN pip install credentialdigger                        0.0s
 => CACHED [ 8/12] RUN pip install gunicorn                                0.0s
 => CACHED [ 9/12] COPY . /credential-digger-ui                            0.0s
 => CACHED [10/12] WORKDIR /credential-digger-ui/                          0.0s
 => CACHED [11/12] RUN find . -type f -print0 | xargs -0 dos2unix          0.0s
 => CACHED [12/12] RUN chmod +x run.sh                                     0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:5f47096b8d80afec9c860308a432ff2175e712759e492  0.0s
 => => naming to docker.io/library/credential-digger_sqlite                0.0s
[+] Running 2/0
 ⠿ Network credential-digger_default   Created                             0.0s
 ⠿ Container credential_digger_sqlite  Created                             0.0s
Attaching to credential_digger_sqlite
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use

**Comment by marcorosa** [comment]
Hi, I think you already have some service blocking port 5000 (maybe another docker container). 

If you cannot stop and remove the other container blocking the port, you can change the port number (in the `docker-compose.yml` file)
