### ISSUE TITLE
Keep line number of a discovery

### ISSUE THREAD

**Issue by marcorosa** [SAP/credential-digger#26]
Add the line number to the attributes of a discovery

NB: this will break the code (non retro compatible change)

**Comment by alaabenfatma** [comment]
Hi @marcorosa,
Should this feature be supported by the UI as well, or just the database (introducing a new column... etc) for the time being? If yes, I can break this into two different PRs.
Adding such an attribute to the discoveries (thus, DB only) will not break the UI per se.

**Comment by marcorosa** [comment]
I think just the database, but this means that we will have to change its structure and the apis... so, I plan to integrate the solution for this issue in v3.0

**Comment by marcorosa** [comment]
WIP in branch `dev/v3-new-UI`

**Comment by marcorosa** [comment]
solved by #69
