### ISSUE TITLE
Error while installing on brand new KALI linux VM

### ISSUE THREAD

**Issue by Essenpreis** [SAP/credential-digger#268]
sudo pip install credentialdigger                                                                                                   
ERROR: Ignored the following versions that require a different python version: 1.0.0 Requires-Python >=3.5, <3.8; 1.0.1 Requires-Python >=3.5, <3.8; 1.0.3 Requires-Python >=3.5, <3.8; 2.0.0 Requires-Python >=3.5, <3.8; 2.1.0 Requires-Python >=3.5, <3.8; 2.1.1 Requires-Python >=3.5, <3.8; 2.2.0 Requires-Python >=3.5, <3.9; 2.2.2 Requires-Python >3.5, <3.9; 3.0.0 Requires-Python >3.5, <3.9; 3.0.1 Requires-Python >3.5, <3.9; 3.0.2 Requires-Python >3.5, <3.9; 3.0.3 Requires-Python >3.5, <3.9; 3.0.4 Requires-Python >3.5, <3.9; 3.0.5 Requires-Python >3.5, <3.9; 3.1.0 Requires-Python >3.5, <3.9; 3.2.0 Requires-Python >3.5, <3.9; 3.3.0 Requires-Python >3.5, <=3.9; 3.3.1 Requires-Python >3.5, <3.10; 3.3.2 Requires-Python >3.5, <3.10; 3.3.3 Requires-Python >3.5, <3.10; 4.0.0 Requires-Python >3.5, <3.10; 4.0.1 Requires-Python >3.5, <3.10; 4.0.2 Requires-Python >3.5, <3.10; 4.0.3 Requires-Python >3.5, <3.10; 4.0.4 Requires-Python >3.5, <3.10; 4.0.5 Requires-Python >3.5, <3.10; 4.1.0 Requires-Python >3.5, <3.10; 4.10.0 Requires-Python >3.5, <3.11; 4.11.0 Requires-Python >3.5, <3.11; 4.11.1 Requires-Python >3.5, <3.11; 4.2.0 Requires-Python >3.5, <3.10; 4.3.0 Requires-Python >3.5, <3.10; 4.3.1 Requires-Python >3.5, <3.10; 4.4.0 Requires-Python >3.5, <3.10; 4.5.0 Requires-Python >3.5, <3.10; 4.5.1 Requires-Python >3.5, <3.10; 4.5.2 Requires-Python >3.5, <3.10; 4.6.0 Requires-Python >3.5, <3.10; 4.6.1 Requires-Python >3.5, <3.10; 4.7.0 Requires-Python >3.5, <3.10; 4.8.0 Requires-Python >3.5, <3.10; 4.8.1 Requires-Python >3.5, <3.10; 4.8.2 Requires-Python >3.5, <3.10; 4.8.3 Requires-Python >3.5, <3.10; 4.9.0 Requires-Python >3.5, <3.10; 4.9.1 Requires-Python >3.5, <3.10; 4.9.2 Requires-Python >3.5, <3.10; 4.9.3 Requires-Python >3.5, <3.11; 4.9.4 Requires-Python >3.5, <3.11; 4.9.5 Requires-Python >3.5, <3.11                             
ERROR: Could not find a version that satisfies the requirement credentialdigger (from versions: none)                                                                                    
ERROR: No matching distribution found for credentialdigger

**Comment by marcorosa** [comment]
Hi, we need more details to debug this issue.
What Kali version are you running and what python version is it installed?

**Comment by Essenpreis** [comment]
Kali 2023.2

python --version
Python 3.11.4

**Comment by Essenpreis** [comment]
I also tried it locally on my Windows machine having

C:\Users\D031105>python --version
Python 3.11.4

Same errors. So it seems to be related with the Python version.

ERROR: Ignored the following versions that require a different python version: 1.0.0 Requires-Python >=3.5, <3.8; 1.0.1 Requires-Python >=3.5, <3.8; 1.0.3 Requires-Python >=3.5, <3.8; 2.0.0 Requires-Python >=3.5, <3.8; 2.1.0 Requires-Python >=3.5, <3.8; 2.1.1 Requires-Python >=3.5, <3.8; 2.2.0 Requires-Python >=3.5, <3.9; 2.2.2 Requires-Python >3.5, <3.9; 3.0.0 Requires-Python >3.5, <3.9; 3.0.1 Requires-Python >3.5, <3.9; 3.0.2 Requires-Python >3.5, <3.9; 3.0.3 Requires-Python >3.5, <3.9; 3.0.4 Requires-Python >3.5, <3.9; 3.0.5 Requires-Python >3.5, <3.9; 3.1.0 Requires-Python >3.5, <3.9; 3.2.0 Requires-Python >3.5, <3.9; 3.3.0 Requires-Python >3.5, <=3.9; 3.3.1 Requires-Python >3.5, <3.10; 3.3.2 Requires-Python >3.5, <3.10; 3.3.3 Requires-Python >3.5, <3.10; 4.0.0 Requires-Python >3.5, <3.10; 4.0.1 Requires-Python >3.5, <3.10; 4.0.2 Requires-Python >3.5, <3.10; 4.0.3 Requires-Python >3.5, <3.10; 4.0.4 Requires-Python >3.5, <3.10; 4.0.5 Requires-Python >3.5, <3.10; 4.1.0 Requires-Python >3.5, <3.10; 4.10.0 Requires-Python >3.5, <3.11; 4.11.0 Requires-Python >3.5, <3.11; 4.11.1 Requires-Python >3.5, <3.11; 4.2.0 Requires-Python >3.5, <3.10; 4.3.0 Requires-Python >3.5, <3.10; 4.3.1 Requires-Python >3.5, <3.10; 4.4.0 Requires-Python >3.5, <3.10; 4.5.0 Requires-Python >3.5, <3.10; 4.5.1 Requires-Python >3.5, <3.10; 4.5.2 Requires-Python >3.5, <3.10; 4.6.0 Requires-Python >3.5, <3.10; 4.6.1 Requires-Python >3.5, <3.10; 4.7.0 Requires-Python >3.5, <3.10; 4.8.0 Requires-Python >3.5, <3.10; 4.8.1 Requires-Python >3.5, <3.10; 4.8.2 Requires-Python >3.5, <3.10; 4.8.3 Requires-Python >3.5, <3.10; 4.9.0 Requires-Python >3.5, <3.10; 4.9.1 Requires-Python >3.5, <3.10; 4.9.2 Requires-Python >3.5, <3.10; 4.9.3 Requires-Python >3.5, <3.11; 4.9.4 Requires-Python >3.5, <3.11; 4.9.5 Requires-Python >3.5, <3.11
ERROR: Could not find a version that satisfies the requirement credentialdigger (from versions: none)
ERROR: No matching distribution found for credentialdigger

**Comment by marcorosa** [comment]
Hi @Essenpreis 
python3.11 is not supported yet, nor is windows. On windows you can run Credential Digger using Docker, whereas for Kali you can use python3.9 (possibly in a virtual environment if you don't want to install another python version on your system)

**Comment by marcorosa** [comment]
With the latest release of credentialdigger (v4.12), python 3.11 support has been introduced (#286). This issue should be solved. Feel free to reopen it in case of need.
