### ISSUE TITLE
Enable optional argument ignore_list for scan_snapshot in credentialdigger cli

### ISSUE THREAD

**Issue by keithlai124** [SAP/credential-digger#312]
Currently the function in `client.scan_snapshot` allows for an optional `ignore_list` argument to be passed in. However, this argument is not available in the credentialdigger cli.

Ideally I want to scan a specified snapshot of a repository but ignore a specific directory in the repository using the credentialdigger cli.

https://github.com/SAP/credential-digger/blob/develop/src/credentialdigger/client.py#L811-L814

https://github.com/SAP/credential-digger/blob/develop/src/credentialdigger/cli/scan_snapshot.py#L121-L131

**Comment by marcorosa** [comment]
Hi, you're right we should add a `--ignore-list` argument in the CLI.
