### ISSUE TITLE
Include Branch name in the scan report export

### ISSUE THREAD

**Issue by ManishYadav-SAP** [SAP/credential-digger#324]
Suggestion: It would be good to include Branch name as well in the scan report export which can help developer to identifies the issue in some large repo which have multiple findings.

**Comment by wassafshahzad** [comment]
Can i pick this up ?

**Comment by SlimTrabelsi** [comment]
Hi @wassafshahzad Yes please 👍

**Comment by wassafshahzad** [comment]
Done

**Comment by marcorosa** [comment]
After thorough consideration, we have determined that implementing this feature is not feasible at this time. The primary reasons are the complexity and potential ambiguity involved in correctly attributing branch names to commits, as discussed in detail in #327 
Given these challenges, we believe that the drawbacks outweigh the potential benefits. As such, we will be closing this issue.  We are always open to new ideas and suggestions. If a viable solution or alternative approach arises in the future, we would welcome the opportunity to revisit this topic. In the meantime, please feel free to share any other feedback or proposals you might have.

**Comment by wassafshahzad** [comment]
> After thorough consideration, we have determined that implementing this feature is not feasible at this time. The primary reasons are the complexity and potential ambiguity involved in correctly attributing branch names to commits, as discussed in detail in #327 Given these challenges, we believe that the drawbacks outweigh the potential benefits. As such, we will be closing this issue. We are always open to new ideas and suggestions. If a viable solution or alternative approach arises in the future, we would welcome the opportunity to revisit this topic. In the meantime, please feel free to share any other feedback or proposals you might have.

Is it ok for me to pick another issue ?

**Comment by marcorosa** [comment]
Yes, of course
