### ISSUE TITLE
Chose between GitPython and PyGithub and support only one of them

### ISSUE THREAD

**Issue by marcorosa** [SAP/credential-digger#54]
At this moment, we are using 2 git libraries: PyGithub and GitPython.
I suggest to just chose one and update the code of the git scanner accordingly.

Why PyGithub
- GitPython is not actively maintained anymore
- It is possible to authenticate with a token (it is needed in many enterprise GitHub or closed gitlab servers)
- it is possible to set the endpoint (thus, it is possible to execute the `scan_user` function not only on github.com)

Why GitPython
- It is possible to call git directly, and this is pivotal [here](https://github.com/SAP/credential-digger/blob/master/credentialdigger/scanners/git_scanner.py#L110-L115)

Considering the points above, I'm inclined towards PyGithub, but only if the diff can be calculated as it is now (i.e., consider only newly added and modified files, ignore submodules, consider only "green" lines in a commit, ignore spaces)

**Comment by marcorosa** [comment]
EDIT: PyGithub uses git APIs. Using APIs it is possible to make a comparison between 2 commits, but it is slower than doing it after cloning the repository, and it's subject to the git API rate. This is to say that if we scan large repositories our requests will exceed the maximum rate and will be timed-out. If they don't get timed-out, the scan will be way slower than doing it with GitPython and generating the diffs between the commits locally.

**Comment by alaabenfatma** [comment]
Hi @marcorosa,
Thank you for pointing out this issue. That said, while I agree on the fact it would be better to use only one module to deal with *git* for maintainability reasons and to require less disk space for the tool to be installed; I think that it is best to keep using the two modules and make them work in tandem the same way they are now. Relying ONLY on PyGithub will introduce a lot of API-related limitations and may cause a heavy performance loss IMO.

**Comment by marcorosa** [comment]
Hi @alaabenfatma, after spending some time checking the documentations of PyGithub and GitPython and making some tests, I have to say that we cannot chose only one of them. At their current stage, they both lack some functionalities that are essential to us. While the support of PyGithub as unique git library seems feasible, even if with some quick and dirty development obligation, it would decrease the performance to an unacceptable level.

I will close this issue.
