### ISSUE TITLE
python setup.py build_ext --pg-config /path/to/pg_config build ...

### ISSUE THREAD

**Issue by mishraanuj205** [SAP/credential-digger#65]
![Screenshot_2020-12-05-21-14-36-38](https://user-images.githubusercontent.com/44110170/101247368-411fc300-373f-11eb-83b4-8e090a81d040.png)

$ pip install -r requirements.txt
Requirement already satisfied: requests in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from -r requirements.txt (line 13)) (2.25.0)
Collecting fasttext
  Using cached fasttext-0.9.2.tar.gz (68 kB)
Requirement already satisfied: pybind11>=2.2 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from fasttext->-r requirements.txt (line 1)) (2.6.1)
Requirement already satisfied: setuptools>=0.7.0 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from fasttext->-r requirements.txt (line 1)) (49.2.1)
Collecting GitPython
  Using cached GitPython-3.1.11-py3-none-any.whl (159 kB)
Collecting hyperscan
  Using cached hyperscan-0.1.5.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting leven
  Downloading leven-1.0.4.tar.gz (20 kB)
Collecting nltk
  Downloading nltk-3.5.zip (1.4 MB)
     |████████████████████████████████| 1.4 MB 561 kB/s
Collecting numpy
  Downloading numpy-1.19.4.zip (7.3 MB)
     |████████████████████████████████| 7.3 MB 88 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pandas
  Downloading pandas-1.1.4.tar.gz (5.2 MB)
     |████████████████████████████████| 5.2 MB 660 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting plac
  Downloading plac-1.2.0-py2.py3-none-any.whl (21 kB)
Collecting psycopg2-binary
  Downloading psycopg2-binary-2.8.6.tar.gz (384 kB)
     |████████████████████████████████| 384 kB 280 kB/s

(Having this problem below)

    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-xv8dea7t/psycopg2-binary_ccc8aff7d25d4791b0f2983a7f36c73c/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-xv8dea7t/psycopg2-binary_ccc8aff7d25d4791b0f2983a7f36c73c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-nwpgb9_8
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-xv8dea7t/psycopg2-binary_ccc8aff7d25d4791b0f2983a7f36c73c/
    Complete output (23 lines):
    running egg_info
    creating /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-nwpgb9_8/psycopg2_binary.egg-info
    writing /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-nwpgb9_8/psycopg2_binary.egg-info/PKG-INFO
    writing dependency_links to /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-nwpgb9_8/psycopg2_binary.egg-info/dependency_links.txt
    writing top-level names to /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-nwpgb9_8/psycopg2_binary.egg-info/top_level.txt
    writing manifest file '/data/data/com.termux/files/usr/tmp/pip-pip-egg-info-nwpgb9_8/psycopg2_binary.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

When I did $ python setup.py build_ext --pg-config $HOME build this pops up
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --pg-config not recognized

Then I did $ python setup.py install 
Then this happened
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/data/data/com.termux/files/usr/tmp/easy_install-w64k7zfv/srsly-2.3.2/setup.py", line 7, in <module>

ModuleNotFoundError: No module named 'Cython'

During handling of the above exception, another exception occurred:
So how do I resolve this problem their is no pkg like libhyperscan-dev in termux please help me

**Comment by marcorosa** [comment]
Hi @mishraanuj205 you're using python3.9, which doesn't support hyperscan. So, try to downgrade python to version 3.8 or 3.7 and retry to install the project. You can also do it with `pip install credentialdigger`.

I don't know what packages termux supports and doesn't support, but if it doesn't support `psycopg2-binary` you can remove it from `requirements.txt` and use only the `SqliteClient`. Anyway, I'm not sure that hyperscan is supported by termux, and without hyperscan the project doesn't work (it is needed by the scanner)

**Comment by Bishwas-py** [comment]
I was also getting the same issue in my Ubuntu device, I got the solution here for [psycopg2 error install ubuntu
](https://webmatrices.com/d/381-psycopg2-error-install-ubuntu)
