### ISSUE TITLE
Wiki : arguments have mismatching names

### ISSUE THREAD

**Issue by alaabenfatma** [SAP/credential-digger#7]
Referring to the wiki page that discusses the approach to follow in order to scan a repo, I have noticed that names of the arguments mismatch those of the constructor.
Wiki page : [How to scan a repository](https://github.com/SAP/credential-digger/wiki/Scan-a-repository)

2. Instantiate the client
   ```python
   from credentialdigger.cli import Client
   c = Client(host='xxx.xxx.xxx.xxx', port=NUM, dbname='mydbname', user='myusername', password='mypassword')
   ```
The constructor : 
```python
  def __init__(self, dbname, dbuser, dbpassword,
                 dbhost='localhost', dbport=5432)
 ```

Code on the wiki page must be : 

 ```python
   from credentialdigger.cli import Client
   c = Client(dbhost='xxx.xxx.xxx.xxx', dbport=NUM, dbname='mydbname', dbuser='myusername', dbpassword='mypassword')
```

**Comment by marcorosa** [comment]
You're right. I fixed the wiki (also in `Scan wiki page` where we had the same inconsistency)

I close this issue.
