### ISSUE TITLE
Server certification verification failed error while cloning public repo.

### ISSUE THREAD

**Issue by 2305ranjan** [SAP/credential-digger#79]
Hi - Thanks for building this tool.

I'm running this locally by following steps mentioned here - https://github.com/SAP/credential-digger#quick-launch

Whole cloning a public repo for scan, I get the following error `Server certification verification failed error while cloning public repo.`

> credential_digger_sqlite | INFO:werkzeug:172.18.0.1 - - [24/Jan/2021 00:52:29] "POST /scan_repo HTTP/1.1" 500 -
> credential_digger_sqlite | Traceback (most recent call last):
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
> credential_digger_sqlite |     return self.wsgi_app(environ, start_response)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
> credential_digger_sqlite |     response = self.handle_exception(e)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
> credential_digger_sqlite |     reraise(exc_type, exc_value, tb)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
> credential_digger_sqlite |     raise value
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
> credential_digger_sqlite |     response = self.full_dispatch_request()
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
> credential_digger_sqlite |     rv = self.handle_user_exception(e)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
> credential_digger_sqlite |     reraise(exc_type, exc_value, tb)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
> credential_digger_sqlite |     raise value
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
> credential_digger_sqlite |     rv = self.dispatch_request()
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
> credential_digger_sqlite |     return self.view_functions[rule.endpoint](**req.view_args)
> credential_digger_sqlite |   File "/credential-digger-ui/server.py", line 137, in scan_repo
> credential_digger_sqlite |     c.scan(repolink, models=models, category=rulesToUse, force=forceScan)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/credentialdigger/client.py", line 592, in scan
> credential_digger_sqlite |     since_commit=from_commit)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/credentialdigger/scanners/git_scanner.py", line 70, in scan
> credential_digger_sqlite |     project_path = self.clone_git_repo(git_url)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/credentialdigger/scanners/base_scanner.py", line 19, in clone_git_repo
> credential_digger_sqlite |     GitRepo.clone_from(git_url, project_path)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/git/repo/base.py", line 1032, in clone_from
> credential_digger_sqlite |     return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/git/repo/base.py", line 973, in _clone
> credential_digger_sqlite |     finalize_process(proc, stderr=stderr)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/git/util.py", line 329, in finalize_process
> credential_digger_sqlite |     proc.wait(**kwargs)
> credential_digger_sqlite |   File "/usr/local/lib/python3.7/site-packages/git/cmd.py", line 408, in wait
> credential_digger_sqlite |     raise GitCommandError(self.args, status, errstr)
> credential_digger_sqlite | git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
> credential_digger_sqlite |   cmdline: git clone -v https://github.com/23ranjan/redis-rack.git /tmp/tmps664dj83
> credential_digger_sqlite |   stderr: 'Cloning into '/tmp/tmps664dj83'...
> credential_digger_sqlite | fatal: unable to access 'https://github.com/23ranjan/redis-rack.git/': server certificate verification failed. CAfile: none CRLfile: none

**Comment by marcorosa** [comment]
Hi @2305ranjan also this issue has been solved with the new release, so I'm gonna close it
