### ISSUE TITLE
Scanning private repo from UI

### ISSUE THREAD

**Issue by 2305ranjan** [SAP/credential-digger#80]
Hi - Is there any way to pass token in UI so as to clone private repos?

I'm running this locally by following steps mentioned here - https://github.com/SAP/credential-digger#quick-launch

but couldn't find any option to pass token or clone a private repo. Thanks.

**Comment by marcorosa** [comment]
Hi @2305ranjan, we are about to release the new version of Credential Digger (v3.0). This new version also includes a brand new user interface that supports the scan of private repositories using git access tokens.
Please wait a couple of days and your issues will be solved ⏳

**Comment by 2305ranjan** [comment]
Great. Thanks again!

**Comment by marcorosa** [comment]
Hi @2305ranjan, your issue has been solved with the new release, that has been published today. Feel free to download it and test it.
